import type { Product, Claim, ExtensionPlan } from './types';

export const products: Product[] = [
  {
    id: 'p1',
    name: 'MacBook Pro 16"',
    brand: 'Apple',
    category: 'Laptop',
    purchaseDate: '2025-11-15',
    warrantyExpiry: '2026-11-15',
    originalWarrantyMonths: 12,
    extendedMonths: 0,
    serialNumber: 'C02XK1QPMD6N',
    retailer: 'Apple Store',
    receiptUploaded: true,
    icon: 'Laptop',
  },
  {
    id: 'p2',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Smartphone',
    purchaseDate: '2025-01-20',
    warrantyExpiry: '2026-08-28',
    originalWarrantyMonths: 12,
    extendedMonths: 6,
    serialNumber: 'RF8M4K2XYZ9',
    retailer: 'Best Buy',
    receiptUploaded: true,
    icon: 'Smartphone',
  },
  {
    id: 'p3',
    name: 'WH-1000XM5 Headphones',
    brand: 'Sony',
    category: 'Audio',
    purchaseDate: '2024-03-10',
    warrantyExpiry: '2025-09-10',
    originalWarrantyMonths: 12,
    extendedMonths: 0,
    serialNumber: 'SN1000XM5-4412',
    retailer: 'Amazon',
    receiptUploaded: true,
    icon: 'Headphones',
  },
  {
    id: 'p4',
    name: 'Dyson V15 Detect',
    brand: 'Dyson',
    category: 'Appliance',
    purchaseDate: '2025-06-01',
    warrantyExpiry: '2028-06-01',
    originalWarrantyMonths: 12,
    extendedMonths: 24,
    serialNumber: 'DY-V15-8820',
    retailer: 'Dyson.com',
    receiptUploaded: false,
    icon: 'Wind',
  },
  {
    id: 'p5',
    name: 'LG C3 OLED 65"',
    brand: 'LG',
    category: 'Television',
    purchaseDate: '2024-09-22',
    warrantyExpiry: '2025-09-22',
    originalWarrantyMonths: 12,
    extendedMonths: 0,
    serialNumber: 'LGC3-65-2024-0922',
    retailer: 'Costco',
    receiptUploaded: true,
    icon: 'Tv',
  },
  {
    id: 'p6',
    name: 'GoPro HERO12 Black',
    brand: 'GoPro',
    category: 'Camera',
    purchaseDate: '2025-02-14',
    warrantyExpiry: '2026-02-14',
    originalWarrantyMonths: 12,
    extendedMonths: 0,
    serialNumber: 'GP-H12-5567',
    retailer: 'B&H Photo',
    receiptUploaded: true,
    icon: 'Camera',
  },
];

export const claims: Claim[] = [
  {
    id: 'c1',
    productId: 'p2',
    productName: 'Galaxy S24 Ultra',
    productIcon: 'Smartphone',
    issue: 'Screen discoloration',
    description: 'Pink tint appeared on the right side of the display after 3 months of use. No drops or damage.',
    status: 'under-review',
    filedDate: '2026-08-15',
    updatedDate: '2026-08-22',
    referenceNumber: 'CLM-2026-0481',
    timeline: [
      { date: '2026-08-15', status: 'pending', note: 'Claim submitted with photos and receipt.' },
      { date: '2026-08-18', status: 'under-review', note: 'Claim assigned to technician for assessment.' },
    ],
  },
  {
    id: 'c2',
    productId: 'p3',
    productName: 'WH-1000XM5 Headphones',
    productIcon: 'Headphones',
    issue: 'Left earcup hinge cracked',
    description: 'Plastic hinge cracked near the swivel joint without impact. Audio still functional.',
    status: 'approved',
    filedDate: '2026-07-01',
    updatedDate: '2026-08-10',
    referenceNumber: 'CLM-2026-0312',
    timeline: [
      { date: '2026-07-01', status: 'pending', note: 'Claim submitted with photos.' },
      { date: '2026-07-05', status: 'under-review', note: 'Photos reviewed by warranty team.' },
      { date: '2026-08-10', status: 'approved', note: 'Replacement approved. Shipping unit to service center.' },
    ],
  },
  {
    id: 'c3',
    productId: 'p5',
    productName: 'LG C3 OLED 65"',
    productIcon: 'Tv',
    issue: 'Vertical banding on panel',
    description: 'Two faint vertical bands visible on light backgrounds. Started appearing recently.',
    status: 'pending',
    filedDate: '2026-08-20',
    updatedDate: '2026-08-20',
    referenceNumber: 'CLM-2026-0517',
    timeline: [
      { date: '2026-08-20', status: 'pending', note: 'Claim submitted. Awaiting initial review.' },
    ],
  },
  {
    id: 'c4',
    productId: 'p1',
    productName: 'MacBook Pro 16"',
    productIcon: 'Laptop',
    issue: 'Battery swelling',
    description: 'Trackpad lifting due to battery swelling. Device still operates but trackpad is unresponsive.',
    status: 'resolved',
    filedDate: '2026-05-02',
    updatedDate: '2026-07-18',
    referenceNumber: 'CLM-2026-0099',
    timeline: [
      { date: '2026-05-02', status: 'pending', note: 'Claim submitted with photos.' },
      { date: '2026-05-06', status: 'under-review', note: 'Diagnostic scheduled at Apple Store.' },
      { date: '2026-05-15', status: 'approved', note: 'Battery replacement approved under warranty.' },
      { date: '2026-07-18', status: 'resolved', note: 'Battery replaced. Device returned to owner.' },
    ],
  },
  {
    id: 'c5',
    productId: 'p6',
    productName: 'GoPro HERO12 Black',
    productIcon: 'Camera',
    issue: 'Water damage despite waterproof rating',
    description: 'Water entered the housing during snorkeling at 2m depth. Device no longer powers on.',
    status: 'rejected',
    filedDate: '2026-06-10',
    updatedDate: '2026-06-25',
    referenceNumber: 'CLM-2026-0205',
    timeline: [
      { date: '2026-06-10', status: 'pending', note: 'Claim submitted.' },
      { date: '2026-06-14', status: 'under-review', note: 'Technician assessed water ingress damage.' },
      { date: '2026-06-25', status: 'rejected', note: 'Claim denied — housing seal was not properly seated per inspection.' },
    ],
  },
];

export const extensionPlans: ExtensionPlan[] = [
  {
    id: 'ext1',
    months: 12,
    label: '1-Year Protection',
    features: ['Parts & labor coverage', 'Accidental damage', 'Priority support'],
  },
  {
    id: 'ext2',
    months: 24,
    label: '2-Year Protection',
    features: ['Everything in 1-Year', 'Battery replacement', 'Free shipping both ways'],
    popular: true,
  },
  {
    id: 'ext3',
    months: 36,
    label: '3-Year Protection',
    features: ['Everything in 2-Year', 'Annual maintenance check', 'Loaner device during repair'],
  },
];
